../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr1 1 100
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr1 101 200
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr1 201 300
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr1 301 400
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr1 401 500
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr1 501 600
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr1 601 700
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr1 701 800
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr2 1 100
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr2 101 200
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr2 201 300
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr2 301 400
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr2 401 500
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr2 501 600
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr3 1 100
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr3 101 200
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr3 201 300
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr3 301 400
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr3 401 500
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr3 501 600
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr4 1 100
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr4 101 200
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr4 201 300
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr5 1 100
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr5 101 200
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr5 201 300
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr5 301 400
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr6 1 100
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr6 101 200
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr6 201 300
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr6 301 400
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr7 1 100
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr7 101 200
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr7 201 300
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr7 301 400
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr7 401 500
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr8 1 100
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr8 101 200
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr8 201 300
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr8 301 400
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr9 1 100
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr9 101 200
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr9 201 300
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr10 1 100
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr10 101 200
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr10 201 300
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr11 1 100
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr11 101 200
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr11 201 300
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr11 301 400
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr11 401 500
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr12 1 100
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr12 101 200
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr12 201 300
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr12 301 400
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr12 401 500
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr12 501 600
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr13 1 100
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr13 101 200
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr14 1 100
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr14 101 200
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr14 201 300
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr14 301 400
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr15 1 100
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr15 101 200
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr15 201 300
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr16 1 100
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr16 101 200
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr16 201 300
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr16 301 400
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr16 401 500
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr17 1 100
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr17 101 200
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr17 201 300
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr17 301 400
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr17 401 500
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr17 501 600
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr18 1 100
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr18 101 200
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr19 1 100
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr19 101 200
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr19 201 300
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr19 301 400
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr19 401 500
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr19 501 600
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr20 1 100
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr20 101 200
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr20 201 300
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr21 1 100
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr22 1 100
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr22 101 200
../../../scripts/sQTLregress.oneexon.cis.R ../input/Geuvadis_exon_info_SE.txt ../input/JC_Geuvadis_DP_SE.txt ../input/JC_Geuvadis_IC_SE.txt Geuvadis_allsnp chr22 201 300
